.Dd December 30, 2020
.Dt ASCII 1
.Os
.
.Sh NAME
.Nm BetterAscii
.Nd ascii command but better
.
.Sh DESCRIPTION
.Nm
Whomsoever wrote this man page is stupid.
Wait... that was a self own wasnt it?....
How do i errase? wait, how can I exit vim?
SEND HELP!!!
.
.Sh SEE ALSO
.Xr Ur Mom 1,
.Xr Ur Mom 2
.
.Sh BUGS
